const state={categories:[],allBoards:[],expandedCategory:null,activeBoard:null,threads:[],activeThread:null,page:{rangeStart:0,rangeEnd:0}};
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const queryUrl=(path,values)=>`${path}?${new URLSearchParams(values)}`;

async function requestJson(url){const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||`読み込みに失敗しました (${response.status})`);return data}
function uniqueBoards(){const map=new Map();for(const category of state.categories)for(const board of category.boards){const item=map.get(board.url)||{...board,categories:[]};if(!item.categories.includes(category.name))item.categories.push(category.name);map.set(board.url,item)}return [...map.values()]}
function renderCategories(){const search=$('boardSearch').value.trim().toLocaleLowerCase();const groups=state.categories.map(category=>{const categoryMatches=category.name.toLocaleLowerCase().includes(search);const boards=category.boards.filter(board=>!search||categoryMatches||`${board.name} ${board.url}`.toLocaleLowerCase().includes(search));if(search&&!categoryMatches&&!boards.length)return '';const expanded=Boolean(search)||state.expandedCategory===category.name;const selected=category.boards.some(board=>board.url===state.activeBoard?.url);const boardRows=expanded?`<div class="category-boards">${boards.map(board=>`<button class="board-button ${state.activeBoard?.url===board.url?'active':''}" type="button" data-board-url="${escapeHtml(board.url)}">${escapeHtml(board.name)}</button>`).join('')}</div>`:'';return `<section class="category-group"><button class="category-button ${selected?'active':''}" type="button" data-category="${escapeHtml(category.name)}" aria-expanded="${expanded}"><span class="category-chevron" aria-hidden="true">›</span><span class="category-name">${escapeHtml(category.name)}</span><small class="category-count">${category.boards.length}</small></button>${boardRows}</section>`}).join('');$('categoryList').innerHTML=groups||'<div class="no-results">カテゴリ・板が見つかりません。</div>';$('categoryTotal').textContent=`${state.categories.length}カテゴリ · ${state.allBoards.length}板`;document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.category;state.expandedCategory=state.expandedCategory===name?null:name;renderCategories()}));document.querySelectorAll('[data-board-url]').forEach(button=>button.addEventListener('click',()=>{const board=state.allBoards.find(item=>item.url===button.dataset.boardUrl);if(board)selectBoard(board)}))}
function setBoardPanel(open){$('boardPanel').classList.toggle('open',open);$('mobileScrim').classList.toggle('open',open);document.body.classList.toggle('panel-open',open)}
function openBoardPanel(){setBoardPanel(true);requestAnimationFrame(()=>document.querySelector('.category-button[aria-expanded="true"]')?.scrollIntoView({block:'center'}))}function closeBoardPanel(){setBoardPanel(false)}

function showBoardView(){ $('welcome').classList.add('hidden');$('readerView').classList.add('hidden');$('boardView').classList.remove('hidden');$('mobileBackToThreads').classList.add('hidden') }
function selectBoard(board){state.activeBoard=board;state.expandedCategory=board.categories?.[0]||state.expandedCategory;state.activeThread=null;state.threads=[];state.page={rangeStart:0,rangeEnd:0};renderCategories();showBoardView();$('boardTitle').textContent=board.name;$('boardCategoryLabel').textContent=board.categories?.[0]||'5ch BOARD';$('boardMeta').textContent='スレッド一覧を読み込み中';$('openBoardSource').href=board.url;$('threadSearch').value='';$('threadCount').textContent='';$('threadList').innerHTML='';$('boardError').classList.add('hidden');$('boardLoading').classList.remove('hidden');closeBoardPanel();window.scrollTo({top:0,behavior:'smooth'});requestJson(queryUrl('/api/board',{url:board.url})).then(data=>{state.threads=data.threads||[];$('boardMeta').textContent=`${data.updatedAt} 取得 ・ 元のスレッド順`;$('boardLoading').classList.add('hidden');renderThreads()}).catch(error=>{$('boardLoading').classList.add('hidden');$('boardError').innerHTML=`スレッド一覧を取得できませんでした。${escapeHtml(error.message)}<br>5ch側の応答を確認して、もう一度お試しください。`;$('boardError').classList.remove('hidden')})}

function renderThreads(){const term=$('threadSearch').value.trim().toLocaleLowerCase();const filtered=state.threads.filter(thread=>!term||thread.title.toLocaleLowerCase().includes(term));$('threadCount').textContent=term?`${filtered.length} / ${state.threads.length} スレッド`:`${state.threads.length} スレッド`;$('noThreads').classList.toggle('hidden',filtered.length>0||state.threads.length===0);$('threadList').innerHTML=filtered.map(thread=>`<article class="thread-row"><button class="thread-open" type="button" data-thread-id="${thread.id}"><span class="thread-title">${escapeHtml(thread.title)}</span><span class="thread-summary">スレッドを開いてレスを読む</span></button><span class="thread-count-chip"><b>${thread.posts??'—'}</b> レス</span><a class="thread-original" href="${escapeHtml(thread.url)}" target="_blank" rel="noopener noreferrer">元スレッドを5chで開く ↗</a></article>`).join('');document.querySelectorAll('[data-thread-id]').forEach(button=>button.addEventListener('click',()=>{const thread=state.threads.find(t=>t.id===button.dataset.threadId);if(thread)openThread(thread)}))}

function showThreadLoading(){ $('boardView').classList.add('hidden');$('welcome').classList.add('hidden');$('readerView').classList.remove('hidden');$('mobileBackToThreads').classList.remove('hidden');$('posts').innerHTML='';$('threadError').classList.add('hidden');$('postsLoading').classList.remove('hidden');$('readerTitle').textContent=state.activeThread?.title||'スレッドを読み込み中';$('readerBoardName').textContent=state.activeBoard?.name||'';$('readerStats').textContent='5chからレスを取得中';window.scrollTo({top:0,behavior:'smooth'}) }
function openThread(thread){state.activeThread=thread;showThreadLoading();loadPostRange(0,0)}
async function loadPostRange(start,end){if(!state.activeThread)return;$('postsLoading').classList.remove('hidden');$('threadError').classList.add('hidden');try{const data=await requestJson(queryUrl('/api/thread',{url:state.activeThread.url,start,end}));state.page={rangeStart:data.rangeStart,rangeEnd:data.rangeEnd};$('readerTitle').textContent=state.activeThread.title;$('readerBoardName').textContent=state.activeBoard?.name||'5ch';$('readerStats').textContent=`${state.activeThread.posts??data.rangeEnd} レス ・ 5ちゃんねる`;$('openThreadSource').href=state.activeThread.url;$('posts').innerHTML=data.posts.length?data.posts.map(post=>`<article class="post" id="res-${post.number}"><div class="post-head"><span class="post-number">${post.number}</span><span class="post-name">${escapeHtml(post.name)}</span><time>${escapeHtml(post.date)}</time></div><div class="post-body">${escapeHtml(post.body)}</div></article>`).join(''):'<div class="no-results">この範囲のレスはありません。</div>';updatePageNavigation();$('postsLoading').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}catch(error){$('postsLoading').classList.add('hidden');$('threadError').innerHTML=`レスを取得できませんでした。${escapeHtml(error.message)}<br><a href="${escapeHtml(state.activeThread.url)}" target="_blank" rel="noopener noreferrer">5chの元スレッドを開く ↗</a>`;$('threadError').classList.remove('hidden')}}

function updatePageNavigation(){const {rangeStart,rangeEnd}=state.page;const total=state.activeThread?.posts||rangeEnd;const label=rangeStart&&rangeEnd?`レス ${rangeStart}–${rangeEnd}`:'レスを表示できません';$('postRange').textContent=label;$('postRangeBottom').textContent=label;const olderDisabled=!rangeStart||rangeStart<=1;const newerDisabled=!rangeEnd||rangeEnd>=total;for(const id of ['olderPosts','olderPostsBottom'])$(id).disabled=olderDisabled;for(const id of ['newerPosts','newerPostsBottom'])$(id).disabled=newerDisabled}
function goOlder(){const start=Math.max(1,state.page.rangeStart-50);const end=state.page.rangeStart-1;if(end>=start)loadPostRange(start,end)}function goNewer(){const start=state.page.rangeEnd+1;const end=Math.min(state.activeThread?.posts||start+49,start+49);if(start<=end)loadPostRange(start,end)}
function backToThreadList(){state.activeThread=null;$('readerView').classList.add('hidden');$('boardView').classList.remove('hidden');$('mobileBackToThreads').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}

async function init(){try{$('boardLoading').classList.add('hidden');const data=await requestJson('/api/menu');state.categories=data.categories||[];state.allBoards=uniqueBoards();const preferred=state.allBoards.find(board=>board.name.includes('プログラム')&&board.url.endsWith('/tech/'))||state.allBoards.find(board=>board.url.endsWith('/livejupiter/'))||state.allBoards[0];if(preferred){state.expandedCategory=state.categories.find(c=>c.boards.some(b=>b.url===preferred.url))?.name||null;renderCategories();$('welcome').classList.add('hidden');selectBoard(preferred)}else{$('categoryTotal').textContent=`${state.categories.length}カテゴリ · ${state.allBoards.length}板`;$('welcome').classList.remove('hidden')}}catch(error){$('welcome').classList.remove('hidden');$('welcome').querySelector('.welcome-copy').textContent=`5chの板一覧を取得できませんでした。${error.message}`;$('categoryTotal').textContent='取得できません'}}

$('openBoards').addEventListener('click',openBoardPanel);$('mobileOpenBoards').addEventListener('click',openBoardPanel);$('mobileBackToThreads').addEventListener('click',backToThreadList);$('welcomeChoose').addEventListener('click',openBoardPanel);$('closeBoards').addEventListener('click',closeBoardPanel);$('mobileScrim').addEventListener('click',closeBoardPanel);$('boardSearch').addEventListener('input',renderCategories);$('threadSearch').addEventListener('input',renderThreads);$('backToThreads').addEventListener('click',backToThreadList);$('olderPosts').addEventListener('click',goOlder);$('olderPostsBottom').addEventListener('click',goOlder);$('newerPosts').addEventListener('click',goNewer);$('newerPostsBottom').addEventListener('click',goNewer);document.addEventListener('keydown',event=>{if(event.key==='Escape')closeBoardPanel()});init();
