const state={categories:[],allBoards:[],expandedCategory:null,activeBoard:null,threads:[],activeThread:null,page:{rangeStart:0,rangeEnd:0},currentPostNumber:0,highlightTimer:null};
let preparedThreadCopy=null;
const BOARD_SEARCH_HISTORY_KEY='5ch-reader-board-search-history';
const PAGE_NAV_SIDE_KEY='5ch-reader-page-nav-side';
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function formatPostBody(value){const body=String(value??'');const pattern=/https?:\/\/[^\s<>"'「」『』【】（）]+|>>\d+(?:-\d+)?/g;let result='',cursor=0,match;while((match=pattern.exec(body))){result+=escapeHtml(body.slice(cursor,match.index));const token=match[0];if(token.startsWith('>>')){const number=token.match(/\d+/)[0];result+=`<a class="post-reference" href="#res-${number}" data-res-id="${number}">${escapeHtml(token)}</a>`}else{const url=token.replace(/[.,!?;:。、，！？]+$/u,'');result+=`<a class="post-link" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(url)}</a>${escapeHtml(token.slice(url.length))}`}cursor=pattern.lastIndex}return result+escapeHtml(body.slice(cursor))}
function highlightPost(post){if(state.highlightTimer){window.clearTimeout(state.highlightTimer);state.highlightTimer=null}document.querySelectorAll('.post.reference-target').forEach(item=>item.classList.remove('reference-target'));post.classList.add('reference-target');state.highlightTimer=window.setTimeout(()=>{post.classList.remove('reference-target');state.highlightTimer=null},2200)}
const queryUrl=(path,values)=>`${path}?${new URLSearchParams(values)}`;

async function requestJson(url){const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data.error||`読み込みに失敗しました (${response.status})`);return data}
function uniqueBoards(){const map=new Map();for(const category of state.categories)for(const board of category.boards){const item=map.get(board.url)||{...board,categories:[]};if(!item.categories.includes(category.name))item.categories.push(category.name);map.set(board.url,item)}return [...map.values()]}
function renderBreadcrumb(target,board,thread=null){const category=board?.categories?.[0]||'5ch';const boardName=board?.name||'';const parts=[`<button class="breadcrumb-link" type="button" data-breadcrumb-category="${escapeHtml(category)}">${escapeHtml(category)}</button>`,`<span class="breadcrumb-separator" aria-hidden="true">›</span>`];if(thread){parts.push(`<button class="breadcrumb-link" type="button" data-breadcrumb-board aria-label="${escapeHtml(boardName)}のスレッド一覧">${escapeHtml(boardName)}</button>`,`<span class="breadcrumb-separator" aria-hidden="true">›</span>`,`<span class="breadcrumb-current" aria-current="page">${escapeHtml(thread.title)}</span>`)}else parts.push(`<span class="breadcrumb-current" aria-current="page">${escapeHtml(boardName)}</span>`);$(target).innerHTML=parts.join('')}
function openCategoryInMenu(name){$('boardSearch').value='';closeBoardSearchHistory();state.expandedCategory=name;renderCategories();openBoardPanel()}
function getBoardSearchHistory(){try{const history=JSON.parse(localStorage.getItem(BOARD_SEARCH_HISTORY_KEY)||'[]');return Array.isArray(history)?history.filter(term=>typeof term==='string'&&term.trim()).slice(0,8):[]}catch{return []}}
function renderBoardSearchHistory(){const history=getBoardSearchHistory();$('clearBoardSearchHistory').disabled=history.length===0;$('boardSearchHistoryList').innerHTML=history.length?history.map(term=>'<div class="search-history-row"><button class="search-history-option" type="button" data-board-search-history="'+escapeHtml(term)+'"><span class="search-history-icon" aria-hidden="true">↻</span><span>'+escapeHtml(term)+'</span></button><button class="search-history-remove" type="button" data-remove-board-search-history="'+escapeHtml(term)+'" aria-label="'+escapeHtml(term)+'を履歴から削除">×</button></div>').join(''):'<p class="search-history-empty">検索履歴はありません</p>'}
function openBoardSearchHistory(){$('boardSearchHistory').classList.remove('hidden');$('boardSearch').setAttribute('aria-expanded','true');renderBoardSearchHistory()}
function closeBoardSearchHistory(){$('boardSearchHistory').classList.add('hidden');$('boardSearch').setAttribute('aria-expanded','false')}
function saveBoardSearchHistory(value){const term=String(value??'').trim();if(!term)return;const history=[term,...getBoardSearchHistory().filter(item=>item!==term)].slice(0,8);try{localStorage.setItem(BOARD_SEARCH_HISTORY_KEY,JSON.stringify(history))}catch{}renderBoardSearchHistory()}
function applyBoardSearchHistory(term){$('boardSearch').value=term;saveBoardSearchHistory(term);closeBoardSearchHistory();renderCategories()}
function clearBoardSearchHistory(){try{localStorage.removeItem(BOARD_SEARCH_HISTORY_KEY)}catch{}renderBoardSearchHistory()}
function removeBoardSearchHistory(term,focusIndex=0){const history=getBoardSearchHistory().filter(item=>item!==term);try{if(history.length)localStorage.setItem(BOARD_SEARCH_HISTORY_KEY,JSON.stringify(history));else localStorage.removeItem(BOARD_SEARCH_HISTORY_KEY)}catch{}renderBoardSearchHistory();const buttons=[...$('boardSearchHistoryList').querySelectorAll('[data-remove-board-search-history]')];(buttons[Math.min(focusIndex,buttons.length-1)]||$('boardSearch')).focus()}
function renderCategories(){const search=$('boardSearch').value.trim().toLocaleLowerCase();const groups=state.categories.map(category=>{const categoryMatches=category.name.toLocaleLowerCase().includes(search);const boards=category.boards.filter(board=>!search||categoryMatches||`${board.name} ${board.url}`.toLocaleLowerCase().includes(search));if(search&&!categoryMatches&&!boards.length)return '';const expanded=Boolean(search)||state.expandedCategory===category.name;const selected=category.boards.some(board=>board.url===state.activeBoard?.url);const boardRows=expanded?`<div class="category-boards">${boards.map(board=>`<button class="board-button ${state.activeBoard?.url===board.url?'active':''}" type="button" data-board-url="${escapeHtml(board.url)}">${escapeHtml(board.name)}</button>`).join('')}</div>`:'';return `<section class="category-group"><button class="category-button ${selected?'active':''}" type="button" data-category="${escapeHtml(category.name)}" aria-expanded="${expanded}"><span class="category-chevron" aria-hidden="true">›</span><span class="category-name">${escapeHtml(category.name)}</span><small class="category-count">${category.boards.length}</small></button>${boardRows}</section>`}).join('');$('categoryList').innerHTML=groups||'<div class="no-results">カテゴリ・板が見つかりません。</div>';$('categoryTotal').textContent=`${state.categories.length}カテゴリ · ${state.allBoards.length}板`;document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{const name=button.dataset.category;state.expandedCategory=state.expandedCategory===name?null:name;renderCategories()}));document.querySelectorAll('[data-board-url]').forEach(button=>button.addEventListener('click',()=>{const board=state.allBoards.find(item=>item.url===button.dataset.boardUrl);if(board){saveBoardSearchHistory($('boardSearch').value);closeBoardSearchHistory();selectBoard(board)}}))}
function setBoardPanel(open){$('boardPanel').classList.toggle('open',open);$('mobileScrim').classList.toggle('open',open);document.body.classList.toggle('panel-open',open)}
function openBoardPanel(){setBoardPanel(true);requestAnimationFrame(()=>document.querySelector('.category-button[aria-expanded="true"]')?.scrollIntoView({block:'center'}))}function closeBoardPanel(){setBoardPanel(false)}
function setPageNavigationSide(side,persist=true){const left=side==='left';$('mobileSideNavigation').classList.toggle('left-handed',left);$('togglePageNavSide').setAttribute('aria-pressed',String(left));$('togglePageNavSide').setAttribute('aria-label',left?'ページ送りを右側に移動（左手モード解除）':'ページ送りを左側に移動（左手モード）');$('togglePageNavSide').title=left?'右手モードに切り替え':'左手モードに切り替え';if(persist){try{localStorage.setItem(PAGE_NAV_SIDE_KEY,left?'left':'right')}catch{}}}

function showBoardView(){document.body.classList.remove('reading');$('welcome').classList.add('hidden');$('readerView').classList.add('hidden');$('boardView').classList.remove('hidden');$('mobileBackToThreads').classList.add('hidden') }
function selectBoard(board){state.activeBoard=board;state.expandedCategory=board.categories?.[0]||state.expandedCategory;state.activeThread=null;state.threads=[];state.page={rangeStart:0,rangeEnd:0};renderCategories();showBoardView();renderBreadcrumb('boardBreadcrumb',board);$('boardTitle').textContent=board.name;$('boardCategoryLabel').textContent='スレッド一覧';$('boardMeta').textContent='スレッド一覧を読み込み中';$('openBoardSource').href=board.url;$('threadSearch').value='';$('threadCount').textContent='';$('threadList').innerHTML='';$('boardError').classList.add('hidden');$('boardLoading').classList.remove('hidden');closeBoardPanel();window.scrollTo({top:0,behavior:'smooth'});requestJson(queryUrl('/api/board',{url:board.url})).then(data=>{state.threads=data.threads||[];$('boardMeta').textContent=`${data.updatedAt} 取得 ・ 元のスレッド順`;$('boardLoading').classList.add('hidden');renderThreads()}).catch(error=>{$('boardLoading').classList.add('hidden');$('boardError').innerHTML=`スレッド一覧を取得できませんでした。${escapeHtml(error.message)}<br>5ch側の応答を確認して、もう一度お試しください。`;$('boardError').classList.remove('hidden')})}

function renderThreads(){const term=$('threadSearch').value.trim().toLocaleLowerCase();const filtered=state.threads.filter(thread=>!term||thread.title.toLocaleLowerCase().includes(term));$('threadCount').textContent=term?`${filtered.length} / ${state.threads.length} スレッド`:`${state.threads.length} スレッド`;$('noThreads').classList.toggle('hidden',filtered.length>0||state.threads.length===0);$('threadList').innerHTML=filtered.map(thread=>`<article class="thread-row"><button class="thread-open" type="button" data-thread-id="${thread.id}"><span class="thread-title">${escapeHtml(thread.title)}</span></button><span class="thread-count-chip"><b>${thread.posts??'—'}</b> レス</span><a class="thread-original" href="${escapeHtml(thread.url)}" target="_blank" rel="noopener noreferrer">元スレッドを5chで開く ↗</a></article>`).join('');document.querySelectorAll('[data-thread-id]').forEach(button=>button.addEventListener('click',()=>{const thread=state.threads.find(t=>t.id===button.dataset.threadId);if(thread)openThread(thread)}))}

function showThreadLoading(){document.body.classList.add('reading');$('boardView').classList.add('hidden');$('welcome').classList.add('hidden');$('readerView').classList.remove('hidden');$('mobileBackToThreads').classList.remove('hidden');$('posts').innerHTML='';$('threadError').classList.add('hidden');$('postsLoading').classList.remove('hidden');$('readerTitle').textContent=state.activeThread?.title||'スレッドを読み込み中';$('readerBoardName').textContent=state.activeBoard?.name||'';renderBreadcrumb('readerBreadcrumb',state.activeBoard,state.activeThread);$('readerStats').textContent='5chからレスを取得中';window.scrollTo({top:0,behavior:'smooth'}) }
function openThread(thread){state.activeThread=thread;state.page={rangeStart:0,rangeEnd:0};state.currentPostNumber=1;showThreadLoading();updatePageNavigation();loadPostRange(1,100,1)}
async function loadPostRange(start,end,targetPostNumber=null){if(!state.activeThread)return;$('postsLoading').classList.remove('hidden');$('threadError').classList.add('hidden');try{const data=await requestJson(queryUrl('/api/thread',{url:state.activeThread.url,start,end}));state.page={rangeStart:data.rangeStart,rangeEnd:data.rangeEnd};state.currentPostNumber=targetPostNumber||data.rangeStart;$('readerTitle').textContent=state.activeThread.title;$('readerBoardName').textContent=state.activeBoard?.name||'5ch';$('openThreadSource').href=state.activeThread.url;$('posts').innerHTML=data.posts.length?data.posts.map(post=>`<article class="post" id="res-${post.number}"><div class="post-head"><span class="post-number">${post.number}</span><span class="post-name">${escapeHtml(post.name)}</span><time>${escapeHtml(post.date)}</time></div><div class="post-body">${formatPostBody(post.body)}</div></article>`).join(''):'<div class="no-results">この範囲のレスはありません。</div>';updatePageNavigation();$('postsLoading').classList.add('hidden');const targetPost=targetPostNumber&&$('res-'+targetPostNumber);if(targetPost){highlightPost(targetPost);targetPost.scrollIntoView({behavior:'smooth',block:'start'})}else{window.scrollTo({top:0,behavior:'smooth'})}}catch(error){$('postsLoading').classList.add('hidden');$('threadError').innerHTML=`レスを取得できませんでした。${escapeHtml(error.message)}<br><a href="${escapeHtml(state.activeThread.url)}" target="_blank" rel="noopener noreferrer">5chの元スレッドを開く ↗</a>`;$('threadError').classList.remove('hidden')}}

async function writeClipboard(text){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(text);return}}catch{}const textarea=document.createElement('textarea');textarea.value=text;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.append(textarea);textarea.select();const copied=document.execCommand('copy');textarea.remove();if(!copied)throw new Error('クリップボードへのコピーに失敗しました')}
function beginClipboardWrite(){if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')return null;let resolveData,rejectData;const data=new Promise((resolve,reject)=>{resolveData=resolve;rejectData=reject});try{const pending=navigator.clipboard.write([new ClipboardItem({'text/plain':data.then(text=>new Blob([text],{type:'text/plain'}))})]);const settled=pending.then(()=>null,error=>error);return{async finish(text){resolveData(text);const error=await settled;if(error)await writeClipboard(text)},cancel(error){rejectData(error)}}}catch{return null}}
async function copyWholeThread(openChatGPT=false){
  const thread=state.activeThread,button=$('copyWholeThread'),chatButton=$('copyAndOpenChatGPT'),status=$('copyThreadStatus');
  if(!thread||button.disabled||chatButton.disabled)return;
  const clipboardWrite=beginClipboardWrite();
  let chatTab=null,threadText='',postCount=0;
  if(openChatGPT){try{chatTab=window.open('about:blank','_blank');if(chatTab){chatTab.opener=null;chatTab.document.title='スレッドを準備中…';chatTab.document.body.textContent='スレッド全体をコピーしています。完了後にChatGPTを開きます。'}}catch{chatTab=null}}
  button.disabled=true;chatButton.disabled=true;status.textContent='スレッド全体を取得しています…';
  try{
    if(preparedThreadCopy?.threadId===thread.id){threadText=preparedThreadCopy.text;postCount=preparedThreadCopy.count}
    else{
      const total=Math.min(1000,Math.max(1,Number(thread.posts)||1000)),postsByNumber=new Map();
      for(let start=1;start<=total;start+=100){
        const end=Math.min(total,start+99);status.textContent=`レス ${start}〜${end} を取得中…`;
        const data=await requestJson(queryUrl('/api/thread',{url:thread.url,start,end}));
        for(const post of data.posts||[])postsByNumber.set(post.number,post);
        if(!data.posts?.length||data.rangeEnd>=total)break;
        if(start+100<=total)await new Promise(resolve=>window.setTimeout(resolve,180));
      }
      const posts=[...postsByNumber.values()].sort((a,b)=>a.number-b.number);
      if(!posts.length)throw new Error('レスが見つかりませんでした');
      const instruction='以下の5ちゃんねるスレッドを、内容の流れが分かるように要約してください。主な論点・意見の違い・結論を整理し、重要な情報を箇条書きでまとめてください。';
      threadText=[instruction,'',`スレッド: ${thread.title}`,`板: ${state.activeBoard?.name||''}`,`URL: ${thread.url}`,'',...posts.map(post=>`>>${post.number} ${post.name}${post.date?` (${post.date})`:''}\n${post.body}`)].join('\n\n');
      postCount=posts.length;preparedThreadCopy={threadId:thread.id,text:threadText,count:postCount};
    }
    if(clipboardWrite)await clipboardWrite.finish(threadText);else await writeClipboard(threadText);
    if(openChatGPT&&chatTab){status.textContent=`全${postCount}レスをコピーしました。ChatGPTを開きます。`;chatTab.location.replace('https://chatgpt.com/')}
    else if(openChatGPT)status.textContent=`全${postCount}レスをコピーしました。新しいタブを開けませんでした。ポップアップを許可して再試行してください。`;
    else status.textContent=`全${postCount}レスをコピーしました。AIに貼り付けて要約できます。`;
  }catch(error){
    clipboardWrite?.cancel(error);
    if(threadText){
      if(openChatGPT&&chatTab){status.textContent=`全${postCount}レスを取得しましたがコピーに失敗しました。もう一度「スレッド全体をコピー」を押してください。ChatGPTを開きます。`;chatTab.location.replace('https://chatgpt.com/')}
      else status.textContent=`コピーに失敗しました。もう一度「スレッド全体をコピー」を押してください。`;
    }else{chatTab?.close();status.textContent=`コピーできませんでした: ${error.message}`}
  }finally{button.disabled=false;chatButton.disabled=false}
}

function updatePageNavigation(current=state.currentPostNumber||state.page.rangeStart){const total=state.activeThread?.posts||state.page.rangeEnd;state.currentPostNumber=current||0;$('postRangeBottom').textContent=current?`レス ${current} / ${total}`:'読み込み中';$('readerStats').textContent=current?`レス ${current} / ${total} ・ 5ちゃんねる`:'5chからレスを取得中';$('readFromStart').disabled=!current||current<=1;$('olderPostsBottom').disabled=!current||current<=1;$('olderPostsSide').disabled=!current||current<=1;$('newerPostsBottom').disabled=!current||current>=total;$('newerPostsSide').disabled=!current||current>=total;$('readToEnd').disabled=!current||current>=total}
function visiblePostNumber(){if(!state.activeThread)return 0;const scanLine=Math.min(48,Math.max(24,window.innerHeight*.06));for(const post of document.querySelectorAll('#posts .post'))if(post.getBoundingClientRect().bottom>scanLine)return Number(post.id.slice(4));return state.page.rangeEnd||0}
function navigateToPost(value){const number=Number(value);if(!Number.isInteger(number)||number<1)return;const currentPost=$(`res-${number}`);if(currentPost){updatePageNavigation(number);highlightPost(currentPost);currentPost.scrollIntoView({behavior:'smooth',block:'start'});return}const total=Number(state.activeThread?.posts)||number;if(number>total)return;const start=Math.floor((number-1)/100)*100+1;const end=Math.min(total,start+99);loadPostRange(start,end,number)}
function goFirst(){const current=visiblePostNumber()||state.currentPostNumber;if(current>1)loadPostRange(1,100,1)}function goLast(){const total=Number(state.activeThread?.posts)||state.page.rangeEnd;if(!total)return;const target=total;if(target>=state.page.rangeStart&&target<=state.page.rangeEnd){navigateToPost(target);return}const start=Math.floor((target-1)/100)*100+1;loadPostRange(start,total,target)}function goOlder(){const current=visiblePostNumber()||state.currentPostNumber||state.page.rangeStart;const target=current-1;if(target<1)return;if(target>=state.page.rangeStart){navigateToPost(target);return}const start=Math.floor((target-1)/100)*100+1;loadPostRange(start,Math.min(state.activeThread?.posts||start+99,start+99),target)}function goNewer(){const current=visiblePostNumber()||state.currentPostNumber||state.page.rangeStart;const target=current+1;const total=Number(state.activeThread?.posts)||state.page.rangeEnd;if(target>total)return;if(target<=state.page.rangeEnd){navigateToPost(target);return}const start=Math.floor((target-1)/100)*100+1;loadPostRange(start,Math.min(total,start+99),target)}
function moveByScreen(direction){if(!state.activeThread)return;const amount=Math.max(240,window.innerHeight-100),maxScroll=Math.max(0,document.documentElement.scrollHeight-window.innerHeight),targetScroll=Math.max(0,Math.min(maxScroll,window.scrollY+direction*amount)),total=Number(state.activeThread.posts)||state.page.rangeEnd;if(direction>0&&targetScroll>=maxScroll-24&&state.page.rangeEnd<total){const start=state.page.rangeEnd+1;loadPostRange(start,Math.min(total,start+99),start);return}if(direction<0&&targetScroll<=24&&state.page.rangeStart>1){const end=state.page.rangeStart-1;loadPostRange(Math.max(1,end-99),end,end);return}window.scrollTo({top:targetScroll,behavior:'smooth'})}
function goOlderPage(){moveByScreen(-1)}function goNewerPage(){moveByScreen(1)}
function backToThreadList(){state.activeThread=null;document.body.classList.remove('reading');$('readerView').classList.add('hidden');$('boardView').classList.remove('hidden');$('mobileBackToThreads').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'})}

async function init(){try{$('boardLoading').classList.add('hidden');const data=await requestJson('/api/menu');state.categories=data.categories||[];state.allBoards=uniqueBoards();const preferred=state.allBoards.find(board=>board.name.includes('プログラム')&&board.url.endsWith('/tech/'))||state.allBoards.find(board=>board.url.endsWith('/livejupiter/'))||state.allBoards[0];if(preferred){state.expandedCategory=state.categories.find(c=>c.boards.some(b=>b.url===preferred.url))?.name||null;renderCategories();$('welcome').classList.add('hidden');selectBoard(preferred)}else{$('categoryTotal').textContent=`${state.categories.length}カテゴリ · ${state.allBoards.length}板`;$('welcome').classList.remove('hidden')}}catch(error){$('welcome').classList.remove('hidden');$('welcome').querySelector('.welcome-copy').textContent=`5chの板一覧を取得できませんでした。${error.message}`;$('categoryTotal').textContent='取得できません'}}

let savedPageNavSide='right';try{savedPageNavSide=localStorage.getItem(PAGE_NAV_SIDE_KEY)==='left'?'left':'right'}catch{}setPageNavigationSide(savedPageNavSide,false);$('togglePageNavSide').addEventListener('click',()=>setPageNavigationSide($('mobileSideNavigation').classList.contains('left-handed')?'right':'left'));
$('copyWholeThread').addEventListener('click',()=>copyWholeThread());$('copyAndOpenChatGPT').addEventListener('click',()=>copyWholeThread(true));
document.addEventListener('click',event=>{const category=event.target.closest('[data-breadcrumb-category]');if(category){openCategoryInMenu(category.dataset.breadcrumbCategory);return}if(event.target.closest('[data-breadcrumb-board]'))backToThreadList()});
$('mobileOpenBoards').addEventListener('click',openBoardPanel);$('readerOpenBoards').addEventListener('click',openBoardPanel);$('mobileBackToThreads').addEventListener('click',backToThreadList);$('welcomeChoose').addEventListener('click',openBoardPanel);$('closeBoards').addEventListener('click',closeBoardPanel);$('mobileScrim').addEventListener('click',closeBoardPanel);$('boardSearch').addEventListener('focus',openBoardSearchHistory);$('boardSearch').addEventListener('input',()=>{renderCategories();if($('boardSearch').value.trim())closeBoardSearchHistory();else openBoardSearchHistory()});$('boardSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){saveBoardSearchHistory($('boardSearch').value);closeBoardSearchHistory()}else if(event.key==='Escape'){closeBoardSearchHistory();event.stopPropagation()}});$('boardSearchHistory').addEventListener('click',event=>{const remove=event.target.closest('[data-remove-board-search-history]');if(remove){const buttons=[...$('boardSearchHistoryList').querySelectorAll('[data-remove-board-search-history]')];removeBoardSearchHistory(remove.dataset.removeBoardSearchHistory,buttons.indexOf(remove));return}const option=event.target.closest('[data-board-search-history]');if(option)applyBoardSearchHistory(option.dataset.boardSearchHistory)});$('clearBoardSearchHistory').addEventListener('click',clearBoardSearchHistory);document.addEventListener('pointerdown',event=>{if(!event.target.closest('.board-search-wrap'))closeBoardSearchHistory()});$('threadSearch').addEventListener('input',renderThreads);$('backToThreads').addEventListener('click',backToThreadList);$('readFromStart').addEventListener('click',goFirst);$('readToEnd').addEventListener('click',goLast);$('olderPostsBottom').addEventListener('click',goOlder);$('newerPostsBottom').addEventListener('click',goNewer);$('olderPostsSide').addEventListener('click',goOlderPage);$('newerPostsSide').addEventListener('click',goNewerPage);$('posts').addEventListener('click',event=>{const reference=event.target.closest('a[data-res-id]');if(reference){event.preventDefault();navigateToPost(reference.dataset.resId)}});let scrollNavigationQueued=false;window.addEventListener('scroll',()=>{if(scrollNavigationQueued||!state.activeThread)return;scrollNavigationQueued=true;window.requestAnimationFrame(()=>{scrollNavigationQueued=false;const current=visiblePostNumber();if(current&&current!==state.currentPostNumber)updatePageNavigation(current)})},{passive:true});document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!$('boardSearchHistory').classList.contains('hidden'))closeBoardSearchHistory();else closeBoardPanel()}});init();
